### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by gpengzhi**
Get rid of python2 in CI.

### CODE REVIEW

**Comment by ZhitingHu** [comment]
Let me first make a new release of Texar before this PR is merged

**Comment by gpengzhi** [comment]
@ZhitingHu Should we merge this now?

**Comment by ZhitingHu** [comment]
Could you first update the version to `0.2.4-unreleased`, including in `version.py`, `setup.py` and `CHANGELOG.md`

**Comment by ZhitingHu** [comment]
> Could you first update the version to `0.2.4-unreleased`, including in `version.py`, `setup.py` and `CHANGELOG.md`

For `CHANGELOG.md`, we usually added the following on top of it:
```
## Unreleased

### New features

### Feature improvements

### Fixes
```

**Comment by gpengzhi** [comment]
> Could you first update the version to `0.2.4-unreleased`, including in `version.py`, `setup.py` and `CHANGELOG.md`

Updated.

**Pull request merged**
